# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

#      - name: Install required modules
#        run: python3 -m pip install setuptools
        
      - name: Install Sphinx Requirements
        working-directory: ${{ github.workspace }}/docs_src
        run: |
          python -m pip install -r requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y pandoc

      # otherwise build will fail as ref data doesnt exist
      - name: Manually edit config file
        working-directory: ${{ github.workspace }}/gtdbtk/config
        run: grep AF_THRESHOLD config.py >  config2.py && mv config2.py config.py
      
      - name: Make the docs
        working-directory: ${{ github.workspace }}/docs_src
        run: make doc

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
